//PRODUCT RELATED
export const GET_ERRORS = "GET_ERRORS";

//TO SET THE CURRENT USER
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//PRODUCT RELATED
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
